version: "3.9"
services:
  mysql-pinocchio:
    container_name: mysql-pinocchio
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hicoders_12
      - MYSQL_PASSWORD=hicoders_12
      - MYSQL_USER=hicoders
      - MYSQL_DATABASE=pinocchio
    volumes:
      - ./mysqlDB:/var/lib/meinsql/data
  phpmyadmin-pinocchio:
    image: phpmyadmin/phpmyadmin
    container_name: pma-pinocchio
    depends_on:
      - mysql-pinocchio
    environment:
      PMA_HOST: mysql-pinocchio
    restart: always
    ports:
      - 8080:80

